-- Military Caste - Gain gold from kills
UPDATE Policies
SET GoldFromKills = '150'
WHERE Type = 'POLICY_MILITARY_CASTE';

-- Plunderer promotion - Gain XP on pillage
INSERT INTO UnitPromotions 
		(Type, 						    Description, 						Help, 									    Sound, 				GainsXPFromPillaging,	AttackWoundedMod,	MovesChange,	PillageBonusStrength, 	AttackMod,	DefenseMod, 	ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 	IconAtlas, 			PediaType, 			PediaEntry)
VALUES	('PROMOTION_WMP_PLUNDERER', 	'TXT_KEY_PROMOTION_WMP_PLUNDERER',	'TXT_KEY_PROMOTION_WMP_PLUNDERER_HELP', 	'AS2D_IF_LEVELUP',	1,						0,					0,				0, 				    	0,			0,				0,					0,			0,					1, 				5, 				'PROMOTION_ATLAS', 	'PEDIA_SHARED',	    'TXT_KEY_PROMOTION_WMP_PLUNDERER_HELP');

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_WMP_PLUNDERER', 'UNITCOMBAT_NAVALRANGED';

-- Professional army - Grants the plunderer promo
INSERT INTO Policy_FreePromotions
	(PolicyType, PromotionType)
VALUES
	('POLICY_PROFESSIONAL_ARMY', 'PROMOTION_WMP_PLUNDERER');
