-- Raiders promotion - When at war, gain great people points and XP when in allied city-state territory
INSERT INTO UnitPromotions 
		(Type, 						        Description, 						        Help, 									    Sound, 				GainsXPFromPillaging,	AttackWoundedMod,	MovesChange,	PillageBonusStrength, 	AttackMod,	DefenseMod, 	ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 	IconAtlas, 			PediaType, 			PediaEntry)
VALUES	('PROMOTION_WMP_MILITARY_ADVISOR', 	'TXT_KEY_PROMOTION_WMP_MILITARY_ADVISOR',	'TXT_KEY_PROMOTION_WMP_MILITARY_ADVISOR', 	'AS2D_IF_LEVELUP',	0,						0,					0,				0, 				    	0,			0,				0,					0,			0,					1, 				5, 				'PROMOTION_ATLAS', 	'PEDIA_SHARED',	    'TXT_KEY_PROMOTION_WMP_MILITARY_ADVISOR_HELP');

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_WMP_MILITARY_ADVISOR', 'UNITCOMBAT_NAVALRANGED';

-- Consulates - Grants the raiders promo
INSERT INTO Policy_FreePromotions
	(PolicyType, PromotionType)
VALUES
	('POLICY_CONSULATES', 'PROMOTION_WMP_MILITARY_ADVISOR');