UPDATE Policies
SET
    InternalTradeRouteYieldModifier = 0
WHERE Type = 'POLICY_THEOCRACY';

INSERT INTO UnitPromotions 
        (Type, 						    Description, 						Help, 									    Sound, 				EnemyHeal,		GainsXPFromPillaging,	AttackWoundedMod,	MovesChange,	PillageBonusStrength, 	AttackMod,	DefenseMod, 	ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 		IconAtlas, 			PediaType, 			PediaEntry)
VALUES	('PROMOTION_WMP_CRUSADER', 	'TXT_KEY_PROMOTION_WMP_CRUSADER',	'TXT_KEY_PROMOTION_WMP_CRUSADER_HELP', 	'AS2D_IF_LEVELUP',	5,				0,						0,					0,				0, 				    	0,			0,				0,					0,			0,					1, 				58, 				'PROMOTION_ATLAS', 	'PEDIA_SHARED',	    'TXT_KEY_PROMOTION_WMP_CRUSADER_HELP');

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_WMP_CRUSADER', 'UNITCOMBAT_NAVALRANGED';

INSERT INTO Policy_FreePromotions (PolicyType, PromotionType)
VALUES ('POLICY_THEOCRACY', 'PROMOTION_WMP_CRUSADER');
